using UnityEngine;
using System;
using System.IO;
using System.Globalization;

namespace RoboIguanaRL {

    /// <summary>
    /// Provides Acces to experimental data about the tail of RoboIguana.
    /// </summary>
    public class TailManager: MonoBehaviour
    {
        [Header("Tail Force Point")]
        public SimpleForcePoint forcePoint;

        /// <summary>
        /// Current forces (x,y,z) generated by the tail.
        /// </summary>
        public Vector3 Force; 

        /// <summary>
        /// Cuurent energy consuption by the tail.
        /// </summary>
        public float EnergyConsumption;

        /// <summary>
        /// Current control parameters of the tail.
        /// </summary>
        public float[] parameters;

        // ######################
        // internal stuff
        // ######################

        /// <summary>
        /// Data path for tail force data.
        /// </summary>
        private string DataPath = "Assets/TailForcePhaseCycleData/";

        /// <summary>
        /// Contains experiment data on forces generated by the tail.
        ///     <remarks>
        ///         [Yaw Amplitude] [Force Drection] [Phase Cycle]
        ///     </remarks>
        /// </summary>
        private float[][][] TailForces;

        /// <summary>
        /// Control parameters to choose from.
        /// </summary>
        private readonly float[][] possibleParameters = new float[][]
        {
            new float[] {0f, 5f, 10f, 15f, 20f, 25f, 30f, 35f, 40f},    // yaw Amps
            new float[] {0f, 0.75f}                                     // frequency
        };

        /// <summary>
        /// Default tail control parameter.
        /// </summary>
        private const float 
                    DefaultPhaseLag = 270f,
                    DefaultSwayAmp = 30f,
                    DefaultFrequency = 0.75f;

        /// <summary>
        /// Marks progress of the tail cycle. Progress is calculated from frequency.
        /// </summary>
        public float phase;

        /// <summary>
        /// Frequency of tail cycles.
        /// </summary>
        public float frequency;

        /// <summary>
        /// Ampltude of yaw in the tail.
        /// </summary>
        public float yawAmplitude;

        /// <summary>
        /// Indices of applied control parameters.
        /// </summary>
        private int[] ParamIdcs;

        /// <summary>
        /// Time step between physics steps.
        /// </summary>
        private float TimeStep;

        /// <summary>
        /// Initializes the tail.
        /// </summary>
        public void Initialize()
        {
            TimeStep  = Time.fixedDeltaTime;
            parameters = new float[] {yawAmplitude, frequency};

            LoadForceData();
            Reset();
            
        }

        /// <summary>
        /// Loads data from experment to provide an estimated force generated by the tail, based on the control parameters.
        /// </summary>
        public void LoadForceData()
        {
            Debug.Log("Loading Tail Forces");
            TailForces = new float[possibleParameters[0].Length][][];

            for (int i = 0; i < possibleParameters[0].Length; i++)
            {
                // get file name
                var yawAmp = possibleParameters[0][i];
                var filename = DataPath + $"yawAmp_{yawAmp}_segment.csv";

                // read file and extract data
                string[] lines = File.ReadAllLines(filename);
                float[][] data = new float[lines.Length - 1][];

                for (int j = 1; j < lines.Length; j++)
                {
                    // skip last line
                    if (string.IsNullOrWhiteSpace(lines[j]))
                    {
                        continue;
                    }

                    string[] columns = lines[j].Split(',');

                    data[j - 1] = new float[2];
                    data[j - 1][0] = float.Parse(columns[0], CultureInfo.InvariantCulture);
                    data[j - 1][1] = float.Parse(columns[1], CultureInfo.InvariantCulture);
                }

                // save data to parameters
                TailForces[i] = data;
            }
        }

        /// <summary>
        /// Resets state of the tail.
        /// </summary>
        public void Reset()
        {
            ParamIdcs = new int[] {0, 0};
            Force = Vector3.zero;
            EnergyConsumption = 0f;
            phase = 0f;
        }

        /// <summary>
        /// Calculates the forces generated by the tail.
        /// </summary>
        public void CalculateForces()
        {
            if (parameters[1] == 0)     // if tail is inactive
            {
                Force.x = 0f; 
                Force.z=0f;
            }
            else                        // if tail is active
            {
                // select relevant float[][]
                var forces = TailForces[ParamIdcs[0]];

                // translate phase to index
                var forceIdx = (int) Math.Round((phase / (Mathf.PI * 2)) * forces[0].Length);

                // Set Values
                Force.x = forces[0][forceIdx];
                Force.y = 0f;
                Force.z = forces[1][forceIdx];
            }
        }

        /// <summary>
        /// Calculates the energy consumed by the tail.
        /// </summary>
        public void CalculateEnergyConsuption()
        {
            return;
        }

        /// <summary>
        /// Sets generated forces and consumed energy according to current parameters.
        /// </summary>
        public void FixedUpdate()
        {
            phase = Mathf.Clamp(phase +  frequency * TimeStep, 0, 2 * Mathf.PI);
            
            CalculateForces();
            CalculateEnergyConsuption();

            forcePoint.ApplyLocalForce(Force);
        }

        /// <summary>
        /// Apply input changes to control parameters.
        /// </summary>
        /// <param name="changes"></param>
        public void UpdateParameters(int[] changes)
        {
            for (int i = 0; i < parameters.Length; i++)
            {
                ParamIdcs[i] = Math.Clamp(ParamIdcs[i] + changes[i], 0, possibleParameters[i].Length-1);
                parameters[i] = possibleParameters[i][ParamIdcs[i]];
            }
        }

    }
}