using UnityEngine;
using Force;

namespace RoboIguanaRL {

    /// <summary>
    /// Provides Acces to experimental data about the tail of RoboIguana.
    /// </summary>
    public class TailManager: MonoBehaviour
    {
        /// <summary>
        /// Current forces (x,y,z) generated by the tail.
        /// </summary>
        public float[] Forces; 

        /// <summary>
        /// Cuurent energy consuption by the tail.
        /// </summary>
        public float EnergyConsumption;

        public float[] ControlParameters {get; set;}

        /// <summary>
        /// Initializes the tail.
        /// </summary>
        public void Initialize(float[] tailParameters)
        {
            ControlParameters = tailParameters;
            Reset();
        }

        /// <summary>
        /// Resets state of the tail.
        /// </summary>
        public void Reset()
        {
            Forces = new float[3] {0f, 0f, 0f};
            EnergyConsumption = 0f;
        }

        /// <summary>
        /// Calculates the forces generated by the tail.
        /// </summary>
        /// <param name="phase"></param>
        public void CalculateForces(float phase, float frequency, float swayAmplitude, float yawAmplitude, float phaseLag)
        {
            return;
        }

        /// <summary>
        /// Calculates the energy consumed by the tail.
        /// </summary>
        /// <param name="phase"></param>
        /// <param name="phaseLag"></param>
        /// <param name="swayAmplitude"></param>
        /// <param name="yawAmplitude"></param>
        public void CalculateEnergyConsuption(float phase, float frequency, float swayAmplitude, float yawAmplitude, float phaseLag)
        {
            return;
        }

        /// <summary>
        /// Sets generated forces and consumed energy according to input parameters.
        /// </summary>
        /// <param name="phase"></param>
        /// <param name="frequency"></param>
        /// <param name="swayAmplitude"></param>
        /// <param name="yawAmplitude"></param>
        /// <param name="phaseLag"></param>
        public void UpdateTail(float phase, float frequency, float swayAmplitude, float yawAmplitude, float phaseLag)
        {
            CalculateForces(phase, frequency, swayAmplitude, yawAmplitude, phaseLag);
            CalculateEnergyConsuption(phase, frequency, swayAmplitude, yawAmplitude, phaseLag);
        }

    }
}